### ISSUE TITLE
out-of-bounds write in coders/pdb.c:691

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#117]
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1542107

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by attritionorg** [comment]
Can you link to the commit please?

**Comment by dlemstra** [comment]
The patch from https://github.com/ImageMagick/ImageMagick/issues/121 should fix this. Can you confirm this @moshekaplan ?

**Comment by moshekaplan** [comment]
This bug appears to still be present. See https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1542107/+attachment/4571526/+files/id%3A000000%2Csig%3A06%2Csrc%3A000000%2Cop%3Aflip1%2Cpos%3A118

**Comment by mikayla-grace** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by moshekaplan** [comment]
This bug appears to have been fixed.

**Comment by attritionorg** [comment]
Can you link to the commit please? Not seeing any that reference #117. Thanks!

**Comment by moshekaplan** [comment]
Probably this one: https://github.com/ImageMagick/ImageMagick/commit/7b93db1807ef8abf0c81df8b0fd047e5fb3f1c3f

**Comment by attritionorg** [comment]
You had previously confirmed the patch from #121 (linked above, 7b93db1) did not fix it, saying it was still present on 2016-02-14. Mikayla-grace said a new patch was coming to fix it on 2016-02-20, which apparently fixed it by your comment earlier today. Just trying to line up the proper commit with the issue. Appreciate any clarification.

**Comment by moshekaplan** [comment]
#121 had several commits. The first commit did not fix the bug. The most recent commit did.

**Comment by attritionorg** [comment]
Ah gotcha, thank you for the clarification!
