### ISSUE TITLE
SVG tspan should not reset X position to 0 by default

### ISSUE THREAD

**Issue by rcanavan** [ImageMagick/ImageMagick#1231]
The SVG below used to be rendered roughly like browsers do in ImageMagick up to about 7.0.7-39, i.e., the separate font styles were rendered one after another in one line.  Even with 2667e84f69b7 (Improve SVG support for tspan element), all tspans of the bottom two lines are rendered on top of each other at x=0.

```
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2400 100" version="1.1">
  <title>FIT SVG Font Rendering Test</title>
   <rect width="100%" height="100%" fill="#ccc"/>

  <text font-size="20px">
	<tspan x="0" dy="1em" font-family="serif">ABCabc123456öäüßÁÇ€☺ (serif)</tspan>
	<tspan x="0" dy="1em" font-family="serif">ABCabc123456öäüßÁÇ€☺ (serif)</tspan>

	<tspan x="0" dy="2em" font-family="sans-serif">sans-serif: <tspan font-weight="bold">bold</tspan>, <tspan font-style="italic">italic</tspan>, <tspan font-weight="bold" font-style="italic">bold/italic</tspan></tspan>
  </text>
</svg>
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment]
Try again, we fixed that issue this morning before we saw your comment.

**Comment by rcanavan** [comment]
The result looks good with a64a7bcf. Thanks!

**Comment by urban-warrior** [comment]
Download the latest patches.  Is it rendering properly now?  It seems to be working for us.

**Comment by rcanavan** [comment]
With 637c396a I still get the question marks. As far as i can tell, they are caused by the whitespace, more specifically, the new lines (0x0a) between the tspans, although tab are rendered as "?" as well:
![p](https://user-images.githubusercontent.com/4719149/43708825-a5ff0f20-996b-11e8-894a-07d88db713d4.png)

[text_svg.zip](https://github.com/ImageMagick/ImageMagick/files/2261954/text_svg.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by rcanavan** [comment]
Looks good to me. Thanks!
