### ISSUE TITLE
Invalid json output for animated gif

### ISSUE THREAD

**Issue by sanmadjack** [ImageMagick/ImageMagick#1624]
ImageMagick 6.9.7-4 .

This command:

 convert -flatten -moments gif:"data/images/71/71b53654ab268339ffd11869224bd9ef" json:

Outputs this:

```
{
  "image": {
    "name": "gif:data/images/71/71b53654ab268339ffd11869224bd9ef",
    "format": "GIF",
    "formatDescription": "CompuServe graphics interchange format",
    "mimeType": "image/gif",
    "class": "DirectClass",
    "geometry": {
      "width": 528,
      "height": 369,
      "x": 0,
      "y": 0
    },
    "units": "Undefined",
    "type": "TrueColor",
    "endianess": "Undefined",
    "colorspace": "sRGB",
    "depth": 8,
    "baseDepth": 8,
    "channelDepth": {
      "red": 8,
      "green": 8,
      "blue": 8
    },
    "pixels": 194832,
    "imageStatistics": {
      "all": {
        "min": "0",
        "max": "255",
        "mean": "108.966",
        "standardDeviation": "40.5291",
        "kurtosis": "1.83414",
        "skewness": "-0.0835711"
      }
    },
    "channelStatistics": {
      "red": {
        "min": "0",
        "max": "255",
        "mean": "123.813",
        "standardDeviation": "39.314",
        "kurtosis": "1.46814",
        "skewness": "-0.301491"
      },
      "green": {
        "min": "0",
        "max": "255",
        "mean": "101.061",
        "standardDeviation": "38.9063",
        "kurtosis": "2.04783",
        "skewness": "0.155652"
      },
      "blue": {
        "min": "0",
        "max": "255",
        "mean": "102.024",
        "standardDeviation": "43.2266",
        "kurtosis": "1.28184",
        "skewness": "-0.0496815"
      }
    },
    "channelMoments": {
      "red": {
        "centroid": {
           "x": "267.523",
           "y": "199.946"
        },
        "ellipseSemiMajorMinorAxis": {
          "x": "306.11",
          "y": "204.59"
        },
        "ellipseAngle": "-0.0505076",
        "ellipseEccentricity": "0.575888",
        "ellipseIntensity": "0.480809",
        "I1": "0.358252",
        "I2": "0.0187737",
        "I3": "1.96712e-05",
        "I4": "9.97922e-05",
        "I5": "-3.85341e-09",
        "I6": "-1.17227e-05",
        "I7": "2.16798e-09",
        "I8": "-3.51906e-06"
      },
      "green": {
        "centroid": {
           "x": "273.511",
           "y": "196.767"
        },
        "ellipseSemiMajorMinorAxis": {
          "x": "305.679",
          "y": "207.613"
        },
        "ellipseAngle": "3.32584",
        "ellipseEccentricity": "0.566403",
        "ellipseIntensity": "0.387287",
        "I1": "0.442084",
        "I2": "0.0265604",
        "I3": "0.000541506",
        "I4": "0.000388147",
        "I5": "-1.10771e-07",
        "I6": "-1.82834e-05",
        "I7": "-1.39268e-07",
        "I8": "-3.02789e-05"
      },
      "blue": {
        "centroid": {
           "x": "280.171",
           "y": "193.464"
        },
        "ellipseSemiMajorMinorAxis": {
          "x": "309.449",
          "y": "205.738"
        },
        "ellipseAngle": "5.02326",
        "ellipseEccentricity": "0.578921",
        "ellipseIntensity": "0.389734",
        "I1": "0.442864",
        "I2": "0.0293645",
        "I3": "0.00182281",
        "I4": "0.000742865",
        "I5": "1.88934e-07",
        "I6": "5.24504e-05",
        "I7": "-8.43544e-07",
        "I8": "-5.7995e-05"
      }
    },
    "channelPerceptualHash": {
      "redHue": {
        "PH1": [ "0.445815", "0.495059" ],
        "PH2": [ "1.72654", "1.73674" ],
        "PH3": [ "4.70561", "2.52264" ],
        "PH4": [ "4.00069", "3.15022" ],
        "PH5": [ "8.41332", "6.00833" ],
        "PH6": [ "4.93087", "4.03415" ],
        "PH7": [ "8.66411", "6.49776" ]
      },
      "greenChroma": {
        "PH1": [ "0.3545", "-0.133504" ],
        "PH2": [ "1.57586", "0.401734" ],
        "PH3": [ "3.26614", "0.856275" ],
        "PH4": [ "3.41088", "1.08158" ],
        "PH5": [ "6.95523", "2.33709" ],
        "PH6": [ "4.73764", "1.28885" ],
        "PH7": [ "6.85585", "2.11801" ]
      },
      "blueLuma": {
        "PH1": [ "0.353735", "0.383513" ],
        "PH2": [ "1.53228", "1.61981" ],
        "PH3": [ "2.73915", "3.53373" ],
        "PH4": [ "3.12899", "3.57576" ],
        "PH5": [ "6.72357", "7.26655" ],
        "PH6": [ "4.28034", "4.8265" ],
        "PH7": [ "6.07369", "7.29652" ]
      }
    },
    "renderingIntent": "Perceptual",
    "gamma": 0.454545,
    "chromaticity": {
      "redPrimary": {
        "x": 0.64,
        "y": 0.33
      },
      "greenPrimary": {
        "x": 0.3,
        "y": 0.6
      },
      "bluePrimary": {
        "x": 0.15,
        "y": 0.06
      },
      "whitePrimary": {
        "x": 0.3127,
        "y": 0.329
      }
    },
    "backgroundColor": "#AA99AC",
    "borderColor": "#DFDFDF",
    "matteColor": "#BDBDBD",
    "transparentColor": "#000000",
    "interlace": "None",
    "intensity": "Undefined",
    "compose": "Over",
    "pageGeometry": {
      "width": 528,
      "height": 369,
      "x": 0,
      "y": 0
    },
    "dispose": "Undefined",
    "delay": "10x100"
    "iterations": 0,
    "compression": "LZW",
    "orientation": "Undefined",
    "properties": {
      "date:create": "2019-06-02T14:41:13-05:00",
      "date:modify": "2019-06-02T14:41:13-05:00",
      "signature": "131d767daa5a4c8be040ca3a29012beb823505a25c2f3a266bd06636f1158339"
    },
    "artifacts": {
      "filename": "gif:data/images/71/71b53654ab268339ffd11869224bd9ef",
      "identify:moments": "gif:data/images/71/71b53654ab268339ffd11869224bd9ef",
      "verbose": "true"
    },
    "tainted": true,
    "filesize": "0B",
    "numberPixels": "195K",
    "pixelsPerSecond": "3.247MB",
    "userTime": "0.910u",
    "elapsedTime": "0:01.059",
    "version": "ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org"
  }
}

```

Specific issue:

    "delay": "10x100"
    "iterations": 0,

There is a comma missing after the delay value, making it invalid json

**Comment by dlemstra** [comment]
This has been fixed a while back: #836. I would advise you to upgrade to the latest version.

**Comment by fmw42** [comment]
FYI, proper syntax would read the input right after convert and before -flatten and -moments. This is just a suggestion, since IM 7 is not going to be so forgiving. See https://imagemagick.org/Usage/basics/#cmdline. Your JSON issue is still valid and proper syntax should not affect the comma issue.
