### ISSUE TITLE
Latest JXL seems to be incompatible

### ISSUE THREAD

**Issue by SoftCreatR** [ImageMagick/ImageMagick#3534]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-8

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04 (64-bit)

### Description

I was able to compile IM with JXL after some struggle (see https://github.com/ImageMagick/ImageMagick/issues/3528) and @dlemstra mentioned, that there might have been API changes in the JXL lib, that may need some investigation. However, it was also mentioned, that IM is compatible with 0.3.3 of JXL, but I am not able to compile JXL 0.3.3 due to some errors (see https://gitlab.com/wg1/jpeg-xl/-/issues/168 + https://gitlab.com/wg1/jpeg-xl/-/issues/175):

```
/usr/local/src/jpeg-xl-v0.3.3/lib/jxl/dec_reconstruct.cc:338:25: error: ‘ensure_padding_filter.jxl::{anonymous}::EnsurePaddingRowByRow::src_x_start_’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

Regardless, we've tested IM with JXL 0.3.7 (current) and it seems, that it's not working:

`convert` seems to work, but it's generating "classic" JPG files (with a .jxl extension).

`> /usr/local/bin/convert -list format`
JXL is not in the list

`> /usr/local/bin/convert -version`
```
Version: ImageMagick 7.0.11-8 Q32 x86_64 2021-04-11 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib
```

`> ls -l /usr/local/lib/ImageMagick-7.0.11/modules-Q32HDRI/coders`
jxl.la and jxl.lo are there.

Everything seems fine at our end, so I guess, there are really some changes in the JXL API, that may need some attention in order to be compatible with IM.

### Steps to Reproduce

1. Compile JXL 0.3.4 or newer
2. Compile IM (as defined at https://github.com/SoftCreatR/imei/blob/main/imei.sh#L627-L681)
3. Convert a file to .jxl

**Comment by SoftCreatR** [comment]
Follow up: 0.3.4 compiles fine, but the problems listed above persist.

**Comment by dlemstra** [comment]
The `--without-utilities` should disable the compliation of the `convert` so I am not sure how you got that working. If you want to use ImageMagick together with `jpeg-xl` I think you will need to do the linking yourself. We cannot do that automatically now because the `pkg-config` they provide us does not work.

**Comment by SoftCreatR** [comment]
> I am not sure how you got that working

I only use `--disable-static`, not `--without-utilities`.

>  I think you will need to do the linking yourself. We cannot do that automatically now because the pkg-config they provide us does not work.

So it means, there's currently no way to make IM work with JXL?

**Comment by SoftCreatR** [comment]
I've opened an issue: https://gitlab.com/wg1/jpeg-xl/-/issues/207

Maybe, things can be sorted.

**Comment by dlemstra** [comment]
I assumed you where still using the static version of ImageMagick. It might work the other way but I will need to investigate that.

**Comment by SoftCreatR** [comment]
I'll see, what I can do. Meanwhile, you may check out my script, where this issue has come to our attention: https://github.com/SoftCreatR/imei/blob/main/imei.sh#L627-L681

**Comment by dlemstra** [comment]
I noticed that you reprository contains "fake commits" with the @magickwizard account. Could you please rewrite those commits in the repository and use your own account for this instead?

**Comment by SoftCreatR** [comment]
Done ;)

**Comment by deymo** [comment]
Hi, what's the issue with jpeg-xl's pkg-config? I get this after installing 0.3.7 jpeg-xl:
```
pkg-config libjxl --cflags --libs --static
-I/usr/local/include -L/usr/local/lib -ljxl -lm -lbrotlienc -lbrotlidec -lbrotlicommon
```

I tried IM from the main branch but I don't see configure.ac using PKG_CHECK_MODULES for libjxl, and yeah the list of static lib dependencies in IM is not present.

Now that I look at that list it looks like we are missing hwy. I think at the time we wrote the .pc file libhwy didn't have one. I'll get that part fixed. But it would be good to know what issues did you find besides that, since this bugs links to -Werror issues that seem unrelated to the .pc.

**Comment by SoftCreatR** [comment]
> since this bugs links to -Werror issues

It was said, that IM should be compatible with JXL 0.3.3, which might be correct, but it's just semi-correct, because the official release of JXL 0.3.3 doesn't build (as described here: https://gitlab.com/wg1/jpeg-xl/-/issues/168 + https://gitlab.com/wg1/jpeg-xl/-/issues/175). However, this is unrelated to the fact, that I can't make JXL and IM work together. Everything else can be found in the main post.

If that helps, I could provide a log file of the whole compilation process.

**Comment by SoftCreatR** [comment]
@dlemstra https://twitter.com/jonsneyers/status/1382434630691913737

**Comment by FossoresLP** [comment]
The same issue just happened to me. After debugging the libtool library loading I found the issue was `JxlThreadParallelRunnerDestroy`. It is not in `libjxl.so` but instead in `libjxl_threads.so`.
By simply adding `LD_PRELOAD=libjxl_threads.so` ImageMagick works correctly and can identify and convert JXL files.
I'm not sure where exactly this issue comes from as I do not normally work with C or libraries but I hope someone else can figure this out.

**Comment by dlemstra** [comment]
This was a mistake in our configuration @FossoresLP. This should be resolved in the latest version with a fix from this PR: #3548

**Comment by FossoresLP** [comment]
@dlemstra Thank you for the tip, I was using 7.0.11-6 just like the author of this issue.
Should this issue be closed then or renamed, because the latest version of libjxl works now?

**Comment by SoftCreatR** [comment]
@FossoresLP That's still questionable. I'm currently building everything to test and report back, when done.

**Comment by SoftCreatR** [comment]
For me, it's still not working. I've updated my initial post and included the current output.

**Comment by FossoresLP** [comment]
@SoftCreatR I just rebuilt with 7.0.11-8, too and it's not working for me either. Could you check if the LD_PRELOAD helps for you, too?

**Comment by deymo** [comment]
Yes, the parallel runner using threads from std::thread are not part of the jxl library because in many cases you want to use your own thread implementation and libjxl.so doesn't depend on libjxl_threads.so. We provide a `libjxl_threads.pc` file as well which should be installed, but I still don't know what's the issue with the .pc files you encountered.

**Comment by SoftCreatR** [comment]
Today, a new commit has been pushed to the JXL repo: https://gitlab.com/wg1/jpeg-xl/-/commit/ab7c5e9b6795134377aa4846ceaae2c5bc504f76

I've rebuilt IM 7.0.11-8 using it, but still no luck (even with `LD_PRELOAD` set).

**Comment by deymo** [comment]
@SoftCreatR , do you have a log output of the build/runtime problem you have?

**Comment by SoftCreatR** [comment]
Here's the full build log. Installed aom + libheif + jxl + ImageMagick on a fresh Ubuntu 20.04 server:

[imei.log](https://github.com/ImageMagick/ImageMagick/files/6353880/imei.log)

**Comment by FossoresLP** [comment]
@SoftCreatR Could you try using JXL explicitly using `LD_PRELOAD=libjxl_threads.so magick identify jxl:<filename>` and post the error message you get, if any?
If it is related to libtool runtime linking (jxl.la not found) then go ahead and run `LD_DEBUG=all magick identify <filename> -debug all> debug.log 2>&1` and upload debug.log and I'll take a look where it all goes wrong and why LD_PRELOAD does not help.

**Comment by SoftCreatR** [comment]
@dlemstra @FossoresLP @deymo 

Just FYI: It works now without any changes at my end using libjxl 0.3.7 and IM 7.0.11-13.
