### ISSUE TITLE
convert Q32 image gives scrambled image

### ISSUE THREAD

**Issue by RichardKirk** [ImageMagick/ImageMagick#3614]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-10 Q32 

### Operating system

MacOS

### Operating system, version and so on

Big Sur 11.3

### Description

With the command...
convert face.fl32 face.png
...face.png looks scrambled. I get similar results with 4-channel and 3-channel images. The supplied face.fl32 has 4 channels. The conversion from .png to .fl32 works.

My current version of ImageMagick was built from source  with...
./configure --with-modules --with-quantum-depth=32

Both files are in the attached test.zip. The .fl32 file looks fine in my software, and looked fine when I could last view it in using 'display'. Apple (resistance is deprecated) have done something to XQuartz which stopped me being able to use 'display' (a separate issue, which I could raise), so I have been trying to use the 'convert' commands instead.

The FL32 support only went in recently [ImageMagick/ImageMagick] FL32 file format (#2847). I am most grateful for this - I have been using 'display' daily until an XTools upgrade apparently knocked X11 support on the head. The thread has some detail on the FL32 format if you need it (it is very simple).

### Steps to Reproduce

convert face.fl32 face.png

Both files are in the attached test.zip. The .fl32 file looks fine in my software, and looked fine when I could last view it in using display.  

### Images

[test.zip](https://github.com/ImageMagick/ImageMagick/files/6406042/test.zip)

**Comment by urban-warrior** [comment]
We confirm your face.fl32 looks proper and we confirm your face.png is gibberish.  However, when we convert your face.fl32 to face.png, we get an except replica as expected.  We're using ImageMagick 7.0.11-10 Q32 under Fedora.  We're not sure why its failing for you.  For ImageMagick 7, the default is HDRI-enabled.  When HDRI is enabled, we recommend a quantum depth or 16: `--with-quantum-depth=16`.  With the Q16 version of ImageMagick, do you get expected results?

**Comment by RichardKirk** [comment]
> On 30 Apr 2021, at 23:29, Cristy ***@***.***> wrote:
> We confirm your face.fl32 looks proper and we confirm your face.png is gibberish. However, when we convert your face.fl32 to face.png, we get an except replica as expected. We're using ImageMagick 7.0.11-10 Q32 under Fedora. We're not sure why its failing for you. For ImageMagick 7, the default is HDRI-enabled. When HDRI is enabled, we recommend a quantum depth or 16: --with-quantum-depth=16. With the Q16 version of ImageMagick, do you get expected results?
> 
> 
Hi.

Thanks for checking. I have just rebuilt using ./configure, omitting the Q32 and -configure-modules.

convert -version
Version: ImageMagick 7.0.11-10 Q16 x86_64 2021-04-24 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib fontconfig freetype gvc heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png raw tiff webp x xml zlib

I am still getting the scrambled image from..
tl-utils ImageCopy face.fl32 face.png

Some machine details FWIW. It’s a bit old (late 2013)..
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	431.0.0.0.0
  SMC Version (system):	2.19f12
  Serial Number (system):	C02MV0YLFD57
  Hardware UUID:	84026D68-F772-5F73-8CC5-BB9FCC9526EA
  Provisioning UDID:	84026D68-F772-5F73-8CC5-BB9FCC9526EA

macOS Big Sur 11.3

Oo! I have just seen there is another Xcode update this morning. Maybe they have fixed something that they broke in the last one, because that was only last week. I will try that next and let you know if it makes a difference.

NB: I forgot to mention I ran ‘make check’ on the 32-bit build and everything passed.

Thanks.
Richard Kirk

**Comment by RichardKirk** [comment]
> On 1 May 2021, at 08:54, Richard Kirk ***@***.***> wrote:
> 
> Oo! I have just seen there is another Xcode update this morning. Maybe they have fixed something that they broke in the last one, because that was only last week. I will try that next and let you know if it makes a difference.

No difference. I could try checking out the code and see if I can spot what’s up. My test image has 4 channels, and it does look like some 3:4 scrambling.

Cheers
Richard

**Comment by urban-warrior** [comment]
@fmw42 can you try converting face.fl32 on your Mac.  Can you reproduce this issue?

**Comment by dlemstra** [comment]
I could reproduce this issue but it looks like moving `ResetImagePixels` after the call to `SetImageExtent` fixed the issue.

**Comment by RichardKirk** [comment]
> On 1 May 2021, at 13:30, Cristy ***@***.***> wrote:
> 
> 
> @fmw42 <https://github.com/fmw42> can you try converting face.fl32 on your Mac. Can you reproduce this issue?
> 
> 

Yes, I can reproduce it…

> open face.png
Original. Looks good. 
> convert face.png face.fl32
> tl-utils ImageCopy face.fl32 face1.png
> open face1.png   
Looks good using my tool.                   
> convert face.fl32 face1.png
> open face1.png             
Looks scrambled.
> emacs face1.png
Sanity check with other viewer. Still looks scrambled.
> convert -version  
Version: ImageMagick 7.0.11-10 Q16 x86_64 2021-04-24 https://imagemagick.org <https://imagemagick.org/>

Sanity check - I was saying Q32,and after recompiling it says Q16, so I am looking at the right version.

I had a quick look at the FL32 coders code. It all looks very tidy, and no sign of confusing 3- and 4- channels.

Bizarre. I could have a look at the data and see if I can work out what had happened.

I am running emacs v27, which should be using ImageMagic for conversions. I can read face.bmp and face.tga, but it does not recognise face.fl32 as an image. Is this expected? Does this give us any clues?

Cheers
Richard

**Comment by fmw42** [comment]
I did a +fft and +ift (to produce real/imaginary components and back again) using FL32 format and it worked just fine. I also used PFM and looked at the two file sizes and they are identical between the two. So if you are having trouble with FL32, you might try using NetPBM PFM format.

**Comment by fmw42** [comment]
Did you try opening a terminal window, launch XQuartz, then use `magick display image.fl32`.  That should work.

**Comment by RichardKirk** [comment]
> On 1 May 2021, at 17:01, Fred Weinhaus ***@***.***> wrote:
> 
> 
> I did a +fft and +ift (to produce real/imaginary components and back again) using FL32 format and it worked just fine. I also used PFM and looked at the two file sizes and they are identical between the two. So if you are having trouble with FL32, you might try using NetPBM PFM format.
> 
I have managed to reproduce the scrambling.

The original image was…
> od -i face.fl32 | head     
0000000         842222662             240             166               4
0000020        1051109031      1051240617      1053609165      1065353216
0000040        1050977445      1051240617      1053345993      1065353216
0000060        1051372203      1051635375      1053740751      1065353216
0000100        1051240617      1051503789      1053740751      1065353216
0000120        1050714273      1050977445      1053214407      1065353216
0000140        1050714273      1051109031      1053345993      1065353216
0000160        1050451101      1050845859      1053214407      1065353216
0000200        1050977445      1051240617      1053872337      1065353216
0000220        1050319515      1050582687      1053345993      1065353216
> convert face.fl32 face1.png
This looked odd.
> convert face1.png face1.fl32
> This looked the same.
> od -i face1.fl32 | head   
0000000         842222662             240             166               3
0000020        1051109031      1051240617      1053609165      1065353216
0000040        1050977445      1051240617      1053345993      1065353216
0000060        1051372203      1051635375      1053740751      1065353216
0000100        1051240617      1051503789      1053740751      1065353216
0000120        1050714273      1050977445      1053214407      1065353216
0000140        1050714273      1051109031      1053345993      1065353216
0000160        1050451101      1050845859      1053214407      1065353216
0000200        1050977445      1051240617      1053872337      1065353216
0000220        1050319515      1050582687      1053345993      1065353216

The dump shows the same float data, here as integers, but the header and the file size are consistent with a 3-channel image. So, it is as if the FL32 reader thinks it is getting 3 channel data in convert face.fl32 face1.png.

I shall go and reply to the other post.

Cheers
Richard

**Comment by fmw42** [comment]
I stand corrected.  The following works:

```
magick lena.png lena.fl32
magick display lena.fl32
```

but the image provided by the OP does not display well. A screen snap looks as follows:

`magick display face.fl32`

![Screen Shot 2021-05-01 at 9 33 53 AM](https://user-images.githubusercontent.com/13458218/116788793-87fcb500-aa60-11eb-92ad-a6d8cd05de19.png)

**Comment by fmw42** [comment]
With IM 7, you should be using magick not convert.

**Comment by RichardKirk** [comment]
> On 1 May 2021, at 17:08, Fred Weinhaus ***@***.***> wrote:
> Did you try opening a terminal window, launch XQuartz, then use magick display image.fl32. That should work.
> 
> 

I have just chucked away the build directory, re-opened the zip file, and started again. My last build was configured without the —with-modules flag, which is what you need for X11.

I have now done just that. I get the same problem as before: the terminal is busy with the command line, but it is not doing anything, and no window ever appears. This started shortly after updating to Xcode 12.4, though I cannot prove any link between the two. I have upgraded again to Xcode 12.5 today, but that did not help.

xcode-select says the command line tools are installed. I have turned the machine off and on again. So that’s me out of ideas. 

I have not opened the display to starting, as I didn’t know whether the problem belonged to ImageMagick, Apple, or Xquartz. I would imagine if all the Apple users were upgrading and seeing this, you would probably know, but maybe I am the first.

Thanks for your efforts.

Cheers
Richard Kirk

**Comment by RichardKirk** [comment]
> On 1 May 2021, at 18:03, Richard Kirk ***@***.***> wrote:
> 
> 
> I get the same problem as before: the terminal is busy with the command line, but it is not doing anything, and no window ever appears.

I forgot to mention that this happened (or didn’t happen) when displaying any file format. I was calling it as ‘display’ but when that stopped working, I tried ‘magic’.

Thanks.
Richard

**Comment by dlemstra** [comment]
This issue has already been fixed... I was on an older version this morning and could reproduce the issue. But with the latest commit the issue has been resolved.

**Comment by RichardKirk** [comment]
> On 1 May 2021, at 18:41, Dirk Lemstra ***@***.***> wrote:
> 
> This issue has already been fixed... I was on an older version this morning and could reproduce the issue. But with the latest commit the issue has been resolved.

Okay. I went to https://github.com/ImageMagick/ImageMagick <https://github.com/ImageMagick/ImageMagick>, and downloaded the zip, which was 7.0.11-10, which is what I had before. Is there a later download I am missing?  I just built this but it seems the same.

Cheers
Richard

**Comment by urban-warrior** [comment]
Clone https://github.com/ImageMagick/ImageMagick.git which is 7.0.11-11 unreleased.  Build, install, and your command should work.  We will have a release of 7.0.11-11 within a day or two if you want to wait.

**Comment by RichardKirk** [comment]
> On 1 May 2021, at 20:24, Cristy ***@***.***> wrote:
> Clone https://github.com/ImageMagick/ImageMagick.git <https://github.com/ImageMagick/ImageMagick.git> which is 7.0.11-11 unreleased. Build, install, and your command should work. We will have a release of 7.0.11-11 within a day or two if you want to wait.
> 
> 

Thank you. I have acquired a new skill: cloning! I have gone up a hat size!

display -version
Version: ImageMagick 7.0.11-11 Q32 x86_64 2021-04-28 https://imagemagick.org <https://imagemagick.org/>

The scrambling no longer happens on the Q16 and the Q32 build.

That has fixed #3614. Thanks.

I still cannot get ‘display’ to do anything, or to get ‘emacs’ to recognise FL32 images, but I am goig again.

Thanks.
Richard Kirk

**Comment by fmw42** [comment]
If you want to get the version of ImageMagick use

`magick -version`

`magick display image.fl32 `

should work to view your image (after launching XQuartz)

**Comment by RichardKirk** [comment]
> On 1 May 2021, at 22:27, Fred Weinhaus ***@***.***> wrote:
> 
> magick display image.fl32

Thanks. I tried this…

> xquartz &
> magic display image.fl32

It does not do anything. Nor does…
> magic display not_a_file

I do get a sensible reply from...
> magic display -version

My XQuartz is vision 2.8.1, which it says is the latest one.

I can raise a separate issue for this, as #3614 is fixed.

Thanks.
Richard Kirk

**Comment by RichardKirk** [comment]
> On 2 May 2021, at 09:52, Richard Kirk ***@***.***> wrote:
> 
> 
> I can raise a separate issue for this, as #3614 is fixed.

Actually, as ‘xclock’ just hangs as well, my hanging problem is between Xorg and Apple.

I still cannot get the ‘emacs’ viewer to recognise FL32 files, but I am learning ‘lisp’ to investigate this. Anyway, if I can get X11 and ‘display’ back, that is a much better viewer than ‘emacs’ IMHO. I am assuming you will tell me if there is an obvious fix, but apart from that, no further replies expected.

Thanks for the support.

Cheers
Richard
