### ISSUE TITLE
Certain Photoshop TIFFs are not handled correctly

### ISSUE THREAD

**Issue by axeld** [ImageMagick/ImageMagick#6058]
### ImageMagick version

7.1.0.57

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

I have a couple of images that are not converted correctly; only parts of the image a visible. It may be caused by Photoshop extensions with respect to layers. Windows Explorer cannot preview the files correctly either. Gimp can open these files just fine, though.

### Steps to Reproduce

Just as an example:
`$ magick broken.tif -thumbnail 500x500 out.png`

### Images

Unfortunately, the image I have is too large for Github (55 MB). I guess you already have a way to deal with large images?

**Comment by urban-warrior** [comment]
Upload the one or more "broken" images on a hosting site and send us a link so we can download it.  We cannot comment further until we can inspect the image(s).

**Comment by axeld** [comment]
The link will only be available for two weeks, but I can create a new one, if needed:
https://dropmefiles.com/R06wP

**Comment by axeld** [comment]
There is no passphrase... I have uploaded it to Dropbox, hopefully this will work out better: https://www.dropbox.com/s/v7q4lxs12ztn3o2/broken.tif?dl=0

BTW, I played with the file a bit more, and they are correctly shown if I use "-alpha off". Obviously, the alpha channel is not correctly handled.

**Comment by fmw42** [comment]
Your Image is CMYK with 4 extra channels. PNG can only have one alpha channel and it will come by default from the first extra channel.

**Comment by axeld** [comment]
I don't understand. What extra 4 channels? The identify output for this file is like this:
```$ magick.exe identify -verbose broken.tif
Image:
  Filename: broken.tif
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 5000x3258+0+0
  Resolution: 300x300
  Print size: 16.6667x10.86
  Units: PixelsPerInch
  Colorspace: CMYK
  Type: ColorSeparationAlpha
  Base type: ColorSeparation
  Endianness: LSB
  Depth: 8-bit
  Channel depth:
    Cyan: 8-bit
    Magenta: 8-bit
    Yellow: 8-bit
    Black: 8-bit
    Alpha: 8-bit
  Channel statistics:
    Pixels: 16290000
    Cyan:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 87 (0.341176)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
    Magenta:
      min: 0  (0)
      max: 232 (0.909804)
      mean: 86.7549 (0.340215)
      median: 81 (0.317647)
      standard deviation: 34.3622 (0.134754)
      kurtosis: 0.857367
      skewness: -0.829367
      entropy: 0.852714
    Yellow:
      min: 0  (0)
      max: 255 (1)
      mean: 98.9957 (0.388218)
      median: 96 (0.376471)
      standard deviation: 37.5079 (0.14709)
      kurtosis: 1.21067
      skewness: -1.1314
      entropy: 0.835117
    Black:
      min: 0  (0)
      max: 249 (0.976471)
      mean: 53.0218 (0.207929)
      median: 31 (0.121569)
      standard deviation: 42.7833 (0.167778)
      kurtosis: 0.514773
      skewness: 0.99769
      entropy: 0.869798
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 108.953 (0.427265)
      median: 255 (1)
      standard deviation: 126.014 (0.494174)
      kurtosis: -1.91222
      skewness: 0.293668
      entropy: 0.202536
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 88.5243 (0.347154)
      median: 110 (0.431373)
      standard deviation: 55.4472 (0.21744)
      kurtosis: 0.610415
      skewness: 0.829558
      entropy: 0.722827
  Total ink density: 329.804%
  Alpha: cmyka(0,0,0,0,0)   #0000000000
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 5000x3258+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: LZW
  Orientation: TopLeft
  Profiles:
    Profile-8bim: 6440 bytes
    Profile-icc: 654352 bytes
    Profile-xmp: 16814 bytes
  Properties:
    date:create: 2023-02-13T11:45:59+00:00
    date:modify: 2023-02-13T11:46:17+00:00
    dc:format: image/tiff
    exif:ColorSpace: 65535
    exif:PixelXDimension: 5000
    exif:PixelYDimension: 3258
    icc:copyright: Copyright 2007 Adobe Systems, Inc.
    icc:description: Coated FOGRA39 (ISO 12647-2:2004)
    photoshop:ColorMode: 4
    photoshop:ICCProfile: Coated FOGRA39 (ISO 12647-2:2004)
    signature: 9f0b47629fb82d770f2b9d0e038526a4365cc92171d05d4cb2b4dbffffa0cc3a
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: separated
    tiff:rows-per-strip: 6
    tiff:software: Adobe Photoshop CS6 (Macintosh)
    tiff:timestamp: 2019:03:27 16:19:53
    xmp:CreateDate: 2019-03-20T14:45:07+01:00
    xmp:CreatorTool: Adobe Photoshop CS6 (Macintosh)
    xmp:MetadataDate: 2019-03-27T16:19:53+01:00
    xmp:ModifyDate: 2019-03-27T16:19:53+01:00
    xmpMM:DerivedFrom: xmp.did:F97F117407206811822ABE484E4D2F2B
    xmpMM:DocumentID: adobe:docid:photoshop:f9cde07b-4ca5-11e9-8999-c84132c53e5b
    xmpMM:InstanceID: xmp.iid:BA992CB13F20681180838E7422121CE5
    xmpMM:OriginalDocumentID: xmp.did:F97F117407206811822ABE484E4D2F2B
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 54.5991MiB
  Number pixels: 16290000
  Pixels per second: 22.938MP
  User time: 2.469u
  Elapsed time: 0:01.710
  Version: ImageMagick 7.0.10-62 Q16 x64 2021-02-07 https://imagemagick.org
```

I see only 5 channels, CMYKA. Could you please elaborate what you mean?
My complete ImageMagick command line I tried with first, looked like this:
`$ magick broken.tif -background none -layers merge +repage -crop 0x0+0+0 -auto-orient -profile sRGB_v4_ICC_preference.icc +profile * -colorspace sRGB -thumbnail 150x150> -strip out.png`

The image looks equally broken when I use JPG (which doesn't support alpha channel at all), but looks correct only when I use `-alpha off` for both cases.

**Comment by fmw42** [comment]
I opened the image in Photoshop where it showed CMYK with 4 extra channels. Imageamgick does not recognize all the extra channels and takes only the first one.

**Comment by urban-warrior** [comment]
The current release of ImageMagick (7.1.0-62) supports the extra meta channels, notice all 8 channels are accounted for:

```
Image:
  Filename: broken.tif
  Permissions: rw-------
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 5000x3258+0+0
  Resolution: 300x300
  Print size: 16.6667x10.86
  Units: PixelsPerInch
  Colorspace: CMYK
  Type: ColorSeparationAlpha
  Base type: ColorSeparation
  Endianness: LSB
  Depth: 8-bit
  Channel depth:
    Cyan: 8-bit
    Magenta: 8-bit
    Yellow: 8-bit
    Black: 8-bit
    Alpha: 8-bit
    Meta channel[0]: 8-bit
    Meta channel[1]: 8-bit
    Meta channel[2]: 8-bit
  Channel statistics:
    Pixels: 16290000
    Cyan:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 98 (0.384314)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
    Magenta:
      min: 0  (0)
      max: 232 (0.909804)
      mean: 86.7549 (0.340215)
      median: 90 (0.352941)
      standard deviation: 34.3622 (0.134754)
      kurtosis: 0.857367
      skewness: -0.829367
      entropy: 0.852714
    Yellow:
      min: 0  (0)
      max: 255 (1)
      mean: 98.9957 (0.388218)
      median: 105 (0.411765)
      standard deviation: 37.5079 (0.14709)
      kurtosis: 1.21067
      skewness: -1.1314
      entropy: 0.835117
    Black:
      min: 0  (0)
      max: 249 (0.976471)
      mean: 53.0218 (0.207929)
      median: 44 (0.172549)
      standard deviation: 42.7833 (0.167778)
      kurtosis: 0.514773
      skewness: 0.99769
      entropy: 0.869798
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 108.953 (0.427265)
      median: 0 (0)
      standard deviation: 126.014 (0.494174)
      kurtosis: -1.91222
      skewness: 0.293668
      entropy: 0.202536
    Meta channel[0]:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 98 (0.384314)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
    Meta channel[1]:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 98 (0.384314)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
    Meta channel[2]:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 98 (0.384314)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 65.2855 (0.256021)
      median: 42.125 (0.165196)
      standard deviation: 58.3404 (0.228786)
      kurtosis: 0.526925
      skewness: 1.15534
      entropy: 0.481156
  Total ink density: 329.804%
  Alpha: cmyka(0,0,0,0,0)   #0000000000
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 5000x3258+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: LZW
  Orientation: TopLeft
  Profiles:
    Profile-8bim: 6440 bytes
    Profile-icc: 654352 bytes
    Profile-iptc: 87 bytes
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      unknown[2,0]: 
    Profile-xmp: 16814 bytes
  Properties:
    date:create: 2023-02-15T00:47:41+00:00
    date:modify: 2023-02-14T20:07:40+00:00
    date:timestamp: 2023-02-15T01:19:45+00:00
    dc:format: image/tiff
    exif:ColorSpace: 65535
    exif:PixelXDimension: 5000
    exif:PixelYDimension: 3258
    icc:copyright: Copyright 2007 Adobe Systems, Inc.
    icc:description: Coated FOGRA39 (ISO 12647-2:2004)
    photoshop:ColorMode: 4
    photoshop:ICCProfile: Coated FOGRA39 (ISO 12647-2:2004)
    signature: 2f658a612ea1690d0515ce75c41c9bbb6f6379b561fc8f786e1a769cd80126e7
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: separated
    tiff:rows-per-strip: 6
    tiff:software: Adobe Photoshop CS6 (Macintosh)
    tiff:timestamp: 2019:03:27 16:19:53
    xmp:CreateDate: 2019-03-20T14:45:07+01:00
    xmp:CreatorTool: Adobe Photoshop CS6 (Macintosh)
    xmp:MetadataDate: 2019-03-27T16:19:53+01:00
    xmp:ModifyDate: 2019-03-27T16:19:53+01:00
    xmpMM:DerivedFrom: xmp.did:F97F117407206811822ABE484E4D2F2B
    xmpMM:DocumentID: adobe:docid:photoshop:f9cde07b-4ca5-11e9-8999-c84132c53e5b
    xmpMM:InstanceID: xmp.iid:BA992CB13F20681180838E7422121CE5
    xmpMM:OriginalDocumentID: xmp.did:F97F117407206811822ABE484E4D2F2B
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 54.5991MiB
  Number pixels: 16.29M
  Pixel cache type: Memory
  Pixels per second: 8.07077MP
  User time: 3.590u
  Elapsed time: 0:03.018
  Version: ImageMagick 7.1.0-63 (Beta) Q16-HDRI x86_64 20889 https://imagemagick.org
```

**Comment by urban-warrior** [comment]
Try this command to get expected results:

```
magick broken.tif -alpha off -colorspace sRGB -thumbnail 500x500 out.png
```

**Comment by fmw42** [comment]
urban-warrior: Thanks for the corrections to my response.

**Comment by axeld** [comment]
Ah, thanks! I hadn't found anything related in the changes list.
Judging from Photoshop, all alpha channels are extra channels. And they are all not enabled, and thus, not visible. Is there any way that I can programmatically detect this?

**Comment by axeld** [comment]
Also, even with 7.1.0-62, %[channels] will still print "cmyka" instead of maybe "cmyka012". Can I retrieve that information via identify -format somehow?

Shouldn't ImageMagick detect non-visible channels, and hide them automatically in the final image? Maybe a new option -auto-hide could be introduced to force this behaviour?

**Comment by fmw42** [comment]
With IM 7 and using magick not convert, it shows the meta channels.



```
magick identify -verbose broken.tif

Image:
  Filename: broken.tif
  Permissions: rw-r--r--
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 5000x3258+0+0
  Resolution: 300x300
  Print size: 16.6667x10.86
  Units: PixelsPerInch
  Colorspace: CMYK
  Type: ColorSeparationAlpha
  Base type: ColorSeparation
  Endianness: LSB
  Depth: 8-bit
  Channel depth:
    Cyan: 8-bit
    Magenta: 8-bit
    Yellow: 8-bit
    Black: 8-bit
    Alpha: 8-bit
    Meta channel[0]: 8-bit
    Meta channel[1]: 8-bit
    Meta channel[2]: 8-bit
  Channel statistics:
    Pixels: 16290000
    Cyan:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 98 (0.384314)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
    Magenta:
      min: 0  (0)
      max: 232 (0.909804)
      mean: 86.7549 (0.340215)
      median: 90 (0.352941)
      standard deviation: 34.3622 (0.134754)
      kurtosis: 0.857367
      skewness: -0.829367
      entropy: 0.852714
    Yellow:
      min: 0  (0)
      max: 255 (1)
      mean: 98.9957 (0.388218)
      median: 105 (0.411765)
      standard deviation: 37.5079 (0.14709)
      kurtosis: 1.21067
      skewness: -1.1314
      entropy: 0.835117
    Black:
      min: 0  (0)
      max: 249 (0.976471)
      mean: 53.0218 (0.207929)
      median: 44 (0.172549)
      standard deviation: 42.7833 (0.167778)
      kurtosis: 0.514773
      skewness: 0.99769
      entropy: 0.869798
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 108.953 (0.427265)
      median: 0 (0)
      standard deviation: 126.014 (0.494174)
      kurtosis: -1.91222
      skewness: 0.293668
      entropy: 0.202536
    Meta channel[0]:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 98 (0.384314)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
    Meta channel[1]:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 98 (0.384314)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
    Meta channel[2]:
      min: 0  (0)
      max: 233 (0.913725)
      mean: 94.8968 (0.372144)
      median: 98 (0.384314)
      standard deviation: 36.5683 (0.143405)
      kurtosis: 1.29669
      skewness: -0.935254
      entropy: 0.853967
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 65.2855 (0.256021)
      median: 42.125 (0.165196)
      standard deviation: 58.3404 (0.228786)
      kurtosis: 0.526925
      skewness: 1.15534
      entropy: 0.481156
  Total ink density: 329.804%
  Alpha: cmyka(0,0,0,0,0)   #0000000000
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 5000x3258+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: LZW
  Orientation: TopLeft
  Profiles:
    Profile-8bim: 6440 bytes
    Profile-icc: 654352 bytes
    Profile-iptc: 87 bytes
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      City[1,90]: 0x00000000: 254700                                        -%G
      unknown[2,0]: 
    Profile-xmp: 16814 bytes
  Properties:
    date:create: 2023-02-15T16:19:32+00:00
    date:modify: 2023-02-14T17:04:46+00:00
    date:timestamp: 2023-02-15T16:19:50+00:00
    dc:format: image/tiff
    exif:ColorSpace: 65535
    exif:PixelXDimension: 5000
    exif:PixelYDimension: 3258
    icc:copyright: Copyright 2007 Adobe Systems, Inc.
    icc:description: Coated FOGRA39 (ISO 12647-2:2004)
    photoshop:ColorMode: 4
    photoshop:ICCProfile: Coated FOGRA39 (ISO 12647-2:2004)
    signature: 2f658a612ea1690d0515ce75c41c9bbb6f6379b561fc8f786e1a769cd80126e7
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: separated
    tiff:rows-per-strip: 6
    tiff:software: Adobe Photoshop CS6 (Macintosh)
    tiff:timestamp: 2019:03:27 16:19:53
    xmp:CreateDate: 2019-03-20T14:45:07+01:00
    xmp:CreatorTool: Adobe Photoshop CS6 (Macintosh)
    xmp:MetadataDate: 2019-03-27T16:19:53+01:00
    xmp:ModifyDate: 2019-03-27T16:19:53+01:00
    xmpMM:DerivedFrom: xmp.did:F97F117407206811822ABE484E4D2F2B
    xmpMM:DocumentID: adobe:docid:photoshop:f9cde07b-4ca5-11e9-8999-c84132c53e5b
    xmpMM:InstanceID: xmp.iid:BA992CB13F20681180838E7422121CE5
    xmpMM:OriginalDocumentID: xmp.did:F97F117407206811822ABE484E4D2F2B
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 54.5991MiB
  Number pixels: 16.29M
  Pixel cache type: Memory
  Pixels per second: 11.9731MP
  User time: 1.270u
  Elapsed time: 0:02.360
  Version: ImageMagick 7.1.0-62 Q16-HDRI aarch64 20885 https://imagemagick.org

```

**Comment by axeld** [comment]
Yes, thanks, I was aware of that since urban-warrior pointed that out.

However, I wanted to know if there is any way to get that information with the -format option. Parsing the complete output programmatically is surely possible, but also not desirable. Also, even this output does not have any information of whether or not the channel should be taken into account in the final image at all. That seems to be completely missing from ImageMagick yet, AFAICT.

**Comment by fmw42** [comment]
I am not sure what you want to extract. But I do not know of any way to get meta channel info other than magick identify -verbose.


`magick broken.tif -format "%[channels]\n" info:`

cmyka

So perhaps it needs to be updated to list the meta channels as well.

**Comment by urban-warrior** [comment]
You can export the meta channels with the FTXT coder.  See http://im.snibgo.com/fmttxt.htm.  You can also move the meta channels to the traditional RGB/CMYK channels with the `-channel-fx` option.

The image is CMYKA with additional meta channels.  ImageMagick declares any channels beyond the standard RGB, RGBA, CMYK, CMYKA, GRAY, etc., as meta channels.  They generally are accessed as channel #'s.  For CMYKA, that's covers channels 0-4.  For channel 5, we reference it as "meta" and you access it as 5, not by mnemonic, e.g., Meta1.

**Comment by axeld** [comment]
I'd say there are three issues in ImageMagick right now:

1. `-format "%[channels]"` does not show meta channels.
2. The intended visibility of channels cannot be determined using ImageMagick at all.
3. ImageMagick does not take visibility of channels into account either, leading to incorrect output when trying to recreate the original image without deep knowledge of the file in question.

I'm not sure you agree on 3.), as this might actually not be the philosophy behind ImageMagick. But if 1.) & 2.) were solved, one could still fix 3.) by being able to retrieve the knowledge to render the image correctly.

**Comment by urban-warrior** [comment]
Tell us what is the "intended visibility" of the channels?  And where is that encoded in the TIFF image?  Your image returns:

```
  Photometric Interpretation: separated
  Extra Samples: 4<unspecified, unspecified, unspecified, unspecified>
```

per the `tiffinfo` utility.  There is nothing much to do when the channels are not tagged other than save them as unspecified meta channels in ImageMagick.

However, we will modify `%[channels]` to mentioned the "unspecified" channels.

**Comment by axeld** [comment]
Nice, thanks! The intended visibility is the one stored in the image. When you open the file in Photoshop, the meta channels are not visible or enabled (the eye icon is missing). They should not be taken into account by default, or at least their intended visibility should be queriable. Unfortunately, I don't know where that information is encoded; it's probably some proprietary Photoshop data.

GIMP does render the image correctly, but does not preserve the alpha channels (there is only one left, and that one is visible, and completely opaque). I don't know if there is some "magic" involved, or if it's just a bug that happens to render the image correctly.

**Comment by fmw42** [comment]
Sorry, but I still do not understand the term "intended visibility".  Please clarify or define that term.

**Comment by axeld** [comment]
Alright, I'll try again: when you open the file in Photoshop, the channels are invisible, because the creator hid them before saving the file. That's their intended visibility. They are part of the file, but are not supposed to be rendered.

**Comment by fmw42** [comment]
So what is it that you want implemented?  Do you just want to know if they are visible or hidden?

**Comment by axeld** [comment]
As I wrote above, it depends. `%[channels]` will apparently soon also show the meta channels. That would have been one request.

The other request would be to be able to tell whether a channel should be made visible or not. Pretty much the same as what is already supported with layers (`%[compose]`). However, I don't know if that information is documented somewhere, or can easily be reverse engineered (I haven't looked at this at all so far, and simply cannot tell).

The final request is more of a suggestion, and depends on the philosophy behind ImageMagick that I'm not entirely familiar with: should the result of `magick input.tiff output.png` closely resemble the image as if I have opened it in Photoshop or show it in Explorer/Finder/whatever? If yes, then the channel visibility should be automatically honored, unless I specify differently via the command line. If not, then I would need to identify the visible channels first, and do that manually via the command line (as it is today, just without being able to access the knowledge of whether a channel should be visible).

**Comment by snibgo** [comment]
> ... should the result of `magick input.tiff output.png` closely resemble the image ...

The channel visibility flag affects whether Photoshop displays the data for that channel. It does not affect whether PS reads or writes that channel data. (I have confirmed this with Gimp. I don't use Photoshop, so can't be sure if that is the same.)

Logically, I think that IM command should do the same: it should read and write channel data irrespective of the value of that flag.

**Comment by axeld** [comment]
@fmw42 well that would simplify the issue, as then the intended visibility would always be hidden.

@snibgo that actually makes sense. However, it would then be great to have a `-auto-hide` or `-auto-visibility` or `-auto-remove` option which automatically discards layers and channels that aren't visible. Or maybe an `-auto-compose` that tries to reproduce only the final image as it would be rendered on screen (just like the already existing `-auto-orient`).

**Comment by fmw42** [comment]
Just use -delete to remove any images past 3 or 4 or 5 depending upon RGB(A) or CMYK(A).  You can delete by channel number, i.e. channels are numbered from 0-X. So -delete 3--1 means from channel 3 to the end.

**Comment by axeld** [comment]
@fmw42 sure, but that still requires to know what I'm doing. If I use ImageMagick programmatically, that is not the case, however, as there is (currently) no way to determine which channels to remove.

And since ImageMagick labels one of the meta channels to be the standard alpha channel, this remains guess work until that is fixed.

**Comment by urban-warrior** [comment]
We have a patch to properly detect whether extra samples include an alpha channel, or not.  The patch will be pushed to main soon.
