### ISSUE TITLE
Windows 11: No decode delegate for this image format 

### ISSUE THREAD

**Issue by blueridgetog** [ImageMagick/ImageMagick#6783]
### ImageMagick version

7.1.1-20

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

Hi. I am struggling here. I appreciate the help and kindness - and direction on how to fix this so I can restore my photographic workflow.

I've used Imagemagick inside Lightroom Classic for many years to help with image exports, applying filenames to proofs among other awesome things. I recently upgraded my xRite color calibration software and it broke Imagemagick's decode deletages (and several other programs). I've removed xRite and fixed the other issues, but Imagemagick still cannot find the delegates. I've downloaded several versions of IM and uninstalled/reinstalled the Windows 11 packages (several versions, include 6.9.12 and 1.1.1-20) to no avail.

No matter how I access IM, using either Lightroom or the IMDisplay utility, I get the same message "no decode delegate for this image format 'JPEG'". I've tried multiple image formats all with the same issue. 

When I run the "magick -list format", it doesn't list any files.

What can I do to get IM to find the delegates? I see examples online for Linux and Mac, but nothing to help in Windows. 

I appreciate any advice or help!

![image](https://github.com/ImageMagick/ImageMagick/assets/147890713/1300d018-8657-4b91-8f22-321a2d818fe0)

Thanks so much!

### Steps to Reproduce

Installed ImageMagick (multiple versions)
Open IMDisplay Utility
Drag a JPEG or PNG file into the display utility
Get the error  message
Uninstall Imagemagick
Reboot laptop
Repeat with same results. 

Run "magick -list format" and I don't see any delegates available.

**Comment by fmw42** [comment]
If you do not see any delegates, then you did not install properly.  Use the binary from Imagemagick to install. See https://imagemagick.org/script/download.php#windows.  Use the install window/GUI to do the install.

**Comment by snibgo** [comment]
You may have multiple installations of IM. Type this command: `where magick`. That will list the installations that are in your path. The first is the one that is executed when you run `magick`.

I suggest removing each installation, then re-install from https://imagemagick.org/script/download.php#windows

**Comment by blueridgetog** [comment]
> If you do not see any delegates, then you did not install properly. Use the binary from Imagemagick to install. See https://imagemagick.org/script/download.php#windows. Use the install window/GUI to do the install.

That's what I thought, too. I have uninstalled the program multiple times and reloaded from the binary from different versions. Each time I get the same results. I've confirmed the uninstallation and rebooted - even waiting several days due to being busy - before trying the installation again from files named like this: ImageMagick-7.1.1-20-Q16-HDRI-x64-dll.exe and ImageMagick-6.9.12-98-Q16-HDRI-x64-dll.exe.

**Comment by blueridgetog** [comment]
> You may have multiple installations of IM. Type this command: `where magick`. That will list the installations that are in your path. The first is the one that is executed when you run `magick`.
> 
> I suggest removing each installation, then re-install from https://imagemagick.org/script/download.php#windows

I wish that was the case. I have completely removed IM from the system multiple times, including just last night. When I run the "where magick" command, it returns: 
![image](https://github.com/ImageMagick/ImageMagick/assets/147890713/f4aae6e6-12d8-4e6b-896e-82ae1f3e3794)

I have reinstalled multiple versions including version 7 and 6 to try and fix this issue.

Thanks for your suggestion: I welcome other ideas! :)

**Comment by fmw42** [comment]
What do you get from 

`magick.exe -version
`

**Comment by blueridgetog** [comment]
> What do you get from
> 
> `magick.exe -version `

Just installed it again from Version: ImageMagick-7.1.1-20-Q16-HDRI-x64-dll.exe

I get this response:

Version: ImageMagick 7.1.1-20 Q16-HDRI x64 98bb1d4:20231008 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193532217)

And then when I load the IM Display tool, I still get this:
![image](https://github.com/ImageMagick/ImageMagick/assets/147890713/5edbb9d3-49e9-4b8b-a6f0-6ffbbf4b1411)

**Comment by fmw42** [comment]
Sorry, I am not a Windows users. So wait for one of them to answer.  I know nothing about the IMDisplay. It looks like all the delegates are there to me.

**Comment by blueridgetog** [comment]
> Sorry, I am not a Windows users. So wait for one of them to answer. I know nothing about the IMDisplay. It looks like all the delegates are there to me.

Thanks for your thoughts and advice.

**Comment by snibgo** [comment]
Check that IMdisplay help (click the "?") gives the expected version number.

There might be a problem with your Windows registry.

I have just now downloaded ImageMagick-7.1.1-20-portable-Q16-HDRI-x86.zip . (Note: installing the "portable" version just copies files, and doesn't change the registry.) IMdisplay works fine.

**Comment by blueridgetog** [comment]
> Check that IMdisplay help (click the "?") gives the expected version number.
> 
> Do the following work?
> 
> ```
> magick rose: r.jpg
> 
> magick r.jpg r.png
> ```
> 
> There might be a problem with your Windows registry.
> 
> On Windows 11, I have just now downloaded ImageMagick-7.1.1-20-portable-Q16-HDRI-x86.zip . (Note: installing the "portable" version just copies files, and doesn't change the registry.) IMdisplay works fine.

Here's the response from the suggested command:
```
magick rose: r.jpg
magick: unable to open image 'rose:': Invalid argument @ error/blob.c/OpenBlob/3573.
magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.
```
I'll pursue the Windows registry and see if there are any entries there for ImageMagick.

**Comment by snibgo** [comment]
On Windows 11, I have downloaded and installed:
```
15/10/2023  18:50        38,841,752 ImageMagick-7.1.1-20-Q16-HDRI-x64-dll.exe
```
... and I can't reproduce the problem.

> magick rose: r.jpg
magick: unable to open image 'rose:': Invalid argument ...

Yikes! The `rose:` image is hard-coded into IM, so shouldn't fail. This is the message we get if we try to read an internal image that doesn't exist, such as:
```
magick qwe: NULL:
magick: unable to open image 'qwe:': Invalid argument @ error/blob.c/OpenBlob/3573.
magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.
```
To help narrow down the problem, can you also try:
```
magick xc: x.jpg

magick gradient: x.jpg
```
Please also show the text output from:
```
magick -list format
```

**Comment by blueridgetog** [comment]
> On Windows 11, I have downloaded and installed:
> 
> ```
> 15/10/2023  18:50        38,841,752 ImageMagick-7.1.1-20-Q16-HDRI-x64-dll.exe
> ```
> 
> ... and I can't reproduce the problem.
> 
> > magick rose: r.jpg
> > magick: unable to open image 'rose:': Invalid argument ...
> 
> Yikes! The `rose:` image is hard-coded into IM, so shouldn't fail. This is the message we get if we try to read an internal image that doesn't exist, such as:
> 
> ```
> magick qwe: NULL:
> magick: unable to open image 'qwe:': Invalid argument @ error/blob.c/OpenBlob/3573.
> magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.
> ```
> 
> To help narrow down the problem, can you also try:
> 
> ```
> magick xc: x.jpg
> 
> magick gradient: x.jpg
> ```
> 
> Please also show the text output from:
> 
> ```
> magick -list format
> ```

I previously have used Magick for years, but the problem started up after I upgraded my color calibration tool a couple weeks ago. I had several issues at the time with image programs (notably Luminar), but narrowed it down to x-rite when I did the magick -list format command and saw a slew of X-rite references. I uninstalled X-Rite and reloaded an older version and Luminar started working, but ImageMagick hasn't recovered. 

I did a fresh uninstall/re-install tonight to run the tests you suggested (thank you!), but this is what I am seeing now:
```
Microsoft Windows [Version 10.0.22621.2428]
(c) Microsoft Corporation. All rights reserved.

C:\Users\xxx>magick
Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}

magick: invalid argument for option  @ error/magick-cli.c/MagickImageCommand/991.

C:\Users\xxx>magick xc: x.jpg
magick: unable to open image 'xc:': Invalid argument @ error/blob.c/OpenBlob/3573.
magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

C:\Users\xxx>magick gradient: x.jpg
magick: unable to open image 'gradient:': Invalid argument @ error/blob.c/OpenBlob/3573.
magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

C:\Users\xxx>magick -list format

C:\Users\xxx>
```

I appreciate your assistance!

**Comment by snibgo** [comment]
So, `magick -list format` shows nothing at all? So IM can't read or write files. And `rose:`, `xc:` etc don't work, so IM can't even read its own built-in images. None of the coders work.

I'm afraid I have no idea what is wrong. But it is, obviously, catastrophic. Reinstalling IM should fix it, but that hasn't worked.

I assume you are running magick from an ordinary command window (aka "Dos" window), not Docker or something?

I also assume that when you did the installation, you told it the directory to contain the installation. And then you didn't move the installed files to a different directory, or different computer, or anything?

And I assume that the same username installed IM, and is running `magick`. If that isn't true, there may be a permissions problem.

Please say if these assumptions are right or wrong.

What is the text output from:
```
magick -list resource
```

At the command line, `where magick` will tell you the directory that contains `magick.exe`. Please post the complete text of `dir /s` of that directory.

If you have the `dll` version, `magick.exe` will be small, eg 25304 bytes, and there will be a subdirectory `modules\coders` containing many DLL files, eg 
```
08/10/2023  21:36           230,104 IM_MOD_RL_magick_.dll
```

If you have the portable version, `magick.exe` will be large, eg 
```
14/10/2023  23:22        20,376,792 magick.exe
```
... and there will be no subdirectories and no DLL files.

**Comment by fmw42** [comment]
Are you on a 32-bit or 64-bit architecture?  Might you have loaded the wrong Imagemagick for your OS?

**Comment by blueridgetog** [comment]
> Are you on a 32-bit or 64-bit architecture? Might you have loaded the wrong Imagemagick for your OS?

64 bit. And installed 64 bit version. Wish it would have been that easy though!

**Comment by ossnorry** [comment]
I'm having this problem too, unusable on w11.

**Comment by HekarKET** [comment]
I followed the instructions on [GitHub](https://github.com/gographics/imagick?tab=readme-ov-file#windows) and faced a similar issue. The problem persisted until I corrected the `MAGICK_CODER_MODULE_PATH` to C:\msys64\mingw64\lib\ImageMagick-7.1.1\modules-Q16HDRI\coders from C:\msys64\mingw64\lib\ImageMagick-7.0.6\modules-Q16HDRI\coders ( mentioned in [documentation ](https://github.com/gographics/imagick?tab=readme-ov-file#windows:~:text=If%20you%20still%20get%20the%20NoDecodeDelegateForThisImageFormat%20error%2C%20then%20make%20sure%20the%20version%20number%20and%20folders%20are%20correct)). This fixed the error for me.

**Comment by MegaCornflakes** [comment]
I was also having this issue previously, until I changed the `MAGICK_CODER_MODULE_PATH` environment variable. It turned out I had installed ImageMagick via Scoop previously, so the variables were set to use the Scoop directory instead of `C:\Program Files\ImageMagick-7.1.1-Q16-HDRI`. Once I did this everything worked fine.

**Comment by LOuroboros** [comment]
I'm getting this problem too when I try to make a .ico file out of a .png one using `magick convert input.png -define icon:auto-resize input.ico `.

I'm using the "ImageMagick-7.1.1-43-portable-Q16-x64.zip" binaries from https://imagemagick.org/script/download.php and don't have multiple installations or anything of the sort.

It was suggested above to check that up by using `where magick`, and mine only throws the folder path in my Windows' PATH variable where I hae the binaries in place.

The full error I'm getting is `magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.` just in case.

Also, I'm using Windows 11 24H2.

**Comment by fmw42** [comment]
On IM 7, use magick, not magick convert. So try

`magick input.png -define icon:auto-resize input.ico`

**Comment by francoisdejgr** [comment]
Greetings
I have the same issue.
I have looked at the questions and submission in this thread. 
Anwers / output below
**Any other info you need or advice?**

Setting MAGICK_CODER_MODULE_PATH did not help.
Version:
Version: ImageMagick 7.1.1-43 Q16-HDRI x64 a2d96f4:20241222 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (194234435)

**This works:**
 magick rose: -crop 40x30+10+10  crop.gif  

**This does not**
magick.exe: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.
test.jpg JPEG 482x373 482x373+0+0 8-bit sRGB 27608B 0.031u 0:00.031

magick test.png: -crop 40x30+10+10  crop.gif 
test.png PNG 482x373 482x373+0+0 8-bit sRGB 62835B 0.000u 0:00.000

**Output from " magick -list format"** 
  Format  Module    Mode  Description
-------------------------------------------------------------------------------
      3FR  DNG       r--   Hasselblad CFV/H3D39II Raw Format (0.21.3-Release)
      3G2  VIDEO     r--   Media Container
      3GP  VIDEO     r--   Media Container
      AAI* AAI       rw+   AAI Dune image
       AI  PDF       rw-   Adobe Illustrator CS2
     APNG  VIDEO     rw+   Animated Portable Network Graphics
      ART* ART       rw-   PFS: 1st Publisher Clip Art
      ARW  DNG       r--   Sony Alpha Raw Format (0.21.3-Release)
   ASHLAR* ASHLAR    -w+   Image sequence laid out in continuous irregular courses
     AVCI  HEIC      ---   AVC Image File Format (1.19.5)
      AVI  VIDEO     r--   Microsoft Audio/Visual Interleaved
     AVIF  HEIC      rw+   AV1 Image File Format (1.19.5)
      AVS* AVS       rw+   AVS X image
    BAYER* BAYER     rw+   Raw mosaiced samples
   BAYERA* BAYER     rw+   Raw mosaiced and alpha samples
      BGR* BGR       rw+   Raw blue, green, and red samples
     BGRA* BGR       rw+   Raw blue, green, red, and alpha samples
     BGRO* BGR       rw+   Raw blue, green, red, and opacity samples
      BIE* JBIG      ---   Joint Bi-level Image experts Group interchange format
      BMP* BMP       rw-   Microsoft Windows bitmap image
     BMP2* BMP       rw-   Microsoft Windows bitmap image (V2)
     BMP3* BMP       rw-   Microsoft Windows bitmap image (V3)
      BRF* BRAILLE   -w-   BRF ASCII Braille format
      CAL* CALS      rw-   Continuous Acquisition and Life-cycle Support Type 1
             Specified in MIL-R-28002 and MIL-PRF-28002
     CALS* CALS      rw-   Continuous Acquisition and Life-cycle Support Type 1
             Specified in MIL-R-28002 and MIL-PRF-28002
   CANVAS* XC        r--   Constant image uniform color
  CAPTION* CAPTION   r--   Caption
      CIN* CIN       rw-   Cineon Image File
      CIP* CIP       -w-   Cisco IP phone image format
     CLIP* CLIP      rw+   Image Clip Mask
CLIPBOARD* CLIPBOARD rw-   The system clipboard
     CMYK* CMYK      rw+   Raw cyan, magenta, yellow, and black samples
    CMYKA* CMYK      rw+   Raw cyan, magenta, yellow, black, and alpha samples
      CR2  DNG       r--   Canon Digital Camera Raw Format (0.21.3-Release)
      CR3  DNG       r--   Canon Digital Camera Raw Format (0.21.3-Release)
      CRW  DNG       r--   Canon Digital Camera Raw Format (0.21.3-Release)
     CUBE* CUBE      r--   Cube LUT
      CUR* ICON      rw-   Microsoft icon
      CUT* CUT       r--   DR Halo
     DATA* INLINE    rw+   Base64-encoded inline images
      DCM* DCM       r--   Digital Imaging and Communications in Medicine image
             DICOM is used by the medical community for images like X-rays.  The
             specification, "Digital Imaging and Communications in Medicine
             (DICOM)", is available at http://medical.nema.org/.  In particular,
             see part 5 which describes the image encoding (RLE, JPEG, JPEG-LS),
             and supplement 61 which adds JPEG-2000 encoding.
      DCR  DNG       r--   Kodak Digital Camera Raw Format (0.21.3-Release)
    DCRAW  DNG       r--   Raw Photo Decoder (dcraw) (0.21.3-Release)
      DCX* PCX       rw+   ZSoft IBM PC multi-page Paintbrush
      DDS* DDS       rw+   Microsoft DirectDraw Surface
    DFONT* TTF       r--   Multi-face font package (Freetype 2.13.3)
     DJVU* DJVU      ---   Deja vu
             See http://www.djvuzone.org/ for details about the DJVU format.  The
             DJVU 1.2 specification is available there and at
             ftp://swrinde.nde.swri.edu/pub/djvu/documents/.
      DNG  DNG       r--   Digital Negative Raw Format (0.21.3-Release)
      DPS  DPS       ---   Display Postscript Interpreter
      DPX* DPX       rw-   SMPTE 268M-2003 (DPX 2.0)
             Digital Moving Picture Exchange Bitmap, Version 2.0.
             See SMPTE 268M-2003 specification at http://www.smtpe.org

     DXT1* DDS       rw+   Microsoft DirectDraw Surface
     DXT5* DDS       rw+   Microsoft DirectDraw Surface
      EMF  EMF       r--   Windows Enhanced Meta File
     EPDF  PDF       rw-   Encapsulated Portable Document Format
      EPI  PS        rw-   Encapsulated PostScript Interchange format
      EPS  PS        rw-   Encapsulated PostScript
     EPS2  PS2       -w-   Level II Encapsulated PostScript
     EPS3  PS3       -w+   Level III Encapsulated PostScript
     EPSF  PS        rw-   Encapsulated PostScript
     EPSI  PS        rw-   Encapsulated PostScript Interchange format
      EPT  EPT       rw-   Encapsulated PostScript with TIFF preview
     EPT2  EPT       rw-   Encapsulated PostScript Level II with TIFF preview
     EPT3  EPT       rw+   Encapsulated PostScript Level III with TIFF preview
      ERF  DNG       r--   Epson Raw Format (0.21.3-Release)
      EXR  EXR       rw-   High Dynamic-range (HDR) (OpenEXR 3.3.2-dev)
 FARBFELD* FARBFELD  rw-   Farbfeld
      FAX* FAX       rw+   Group 3 FAX
             FAX machines use non-square pixels which are 1.5 times wider than
             they are tall but computer displays use square pixels, therefore
             FAX images may appear to be narrow unless they are explicitly
             resized using a geometry of "150x100%".

       FF* FARBFELD  rw-   Farbfeld
      FFF  DNG       r--   Hasselblad CFV/H3D39II Raw Format (0.21.3-Release)
     FILE* URL       r--   Uniform Resource Locator (file://)
     FITS* FITS      rw+   Flexible Image Transport System
     FL32* FL32      rw-   FilmLight
     FLIF* FLIF      rw+   Free Lossless Image Format (libflif 0.0.2 [0000])
      FLV  VIDEO     rw+   Flash Video Stream
      FPX  FPX       ---   FlashPix Format
  FRACTAL* PLASMA    r--   Plasma fractal image
      FTP* URL       r--   Uniform Resource Locator (ftp://)
      FTS* FITS      rw+   Flexible Image Transport System
     FTXT* FTXT      rw-   Formatted text image
       G3* FAX       rw-   Group 3 FAX
       G4* FAX       rw-   Group 4 FAX
      GIF* GIF       rw+   CompuServe graphics interchange format
    GIF87* GIF       rw-   CompuServe graphics interchange format (version 87a)
 GRADIENT* GRADIENT  r--   Gradual linear passing from one shade to another
     GRAY* GRAY      rw+   Raw gray samples
    GRAYA* GRAY      rw+   Raw gray and alpha samples
   GROUP4* TIFF      rw-   Raw CCITT Group4
             Compression options: None, Fax/Group3, Group4, JBIG, JPEG, LERC, LZW, LZMA, RLE, ZIP, ZSTD, WEBP
     HALD* HALD      r--   Identity Hald color lookup table image
      HDR* HDR       rw+   Radiance RGBE image format
     HEIC  HEIC      r--   High Efficiency Image Format (1.19.5)
     HEIF  HEIC      r--   High Efficiency Image Format (1.19.5)
HISTOGRAM* HISTOGRAM -w-   Histogram of the image
      HRZ* HRZ       rw-   Slow Scan TeleVision
      HTM* HTML      -w-   Hypertext Markup Language and a client-side image map
     HTML* HTML      -w-   Hypertext Markup Language and a client-side image map
     HTTP* URL       r--   Uniform Resource Locator (http://)
    HTTPS* URL       r--   Uniform Resource Locator (https://)
      ICB* TGA       rw-   Truevision Targa image
      ICO* ICON      rw+   Microsoft icon
     ICON* ICON      rw-   Microsoft icon
      IIQ  DNG       r--   Phase One Raw Format (0.21.3-Release)
     INFO  INFO      -w+   The image format and characteristics
   INLINE* INLINE    rw+   Base64-encoded inline images
      IPL* IPL       rw+   IPL Image Sequence
   ISOBRL* BRAILLE   -w-   ISO/TR 11548-1 format
  ISOBRL6* BRAILLE   -w-   ISO/TR 11548-1 format 6dot
      J2C* JP2       rw-   JPEG-2000 Code Stream Syntax (2.5.2)
      J2K* JP2       rw-   JPEG-2000 Code Stream Syntax (2.5.2)
      JBG* JBIG      ---   Joint Bi-level Image experts Group interchange format
     JBIG* JBIG      ---   Joint Bi-level Image experts Group interchange format
      JNG* PNG       rw-   JPEG Network Graphics
             See http://www.libpng.org/pub/mng/ for details about the JNG
             format.
      JNX* JNX       r--   Garmin tile format
      JP2* JP2       rw-   JPEG-2000 File Format Syntax (2.5.2)
      JPC* JP2       rw-   JPEG-2000 Code Stream Syntax (2.5.2)
      JPE* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 3.0.3)
     JPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 3.0.3)
      JPG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 3.0.3)
      JPM* JP2       rw-   JPEG-2000 File Format Syntax (2.5.2)
      JPS* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 3.0.3)
      JPT* JP2       rw-   JPEG-2000 File Format Syntax (2.5.2)
     JSON  JSON      -w+   The image format and characteristics
      JXL* JXL       rw+   JPEG XL (ISO/IEC 18181) (libjxl 0.11.1)
      K25  DNG       r--   Kodak Digital Camera Raw Format (0.21.3-Release)
      KDC  DNG       r--   Kodak Digital Camera Raw Format (0.21.3-Release)
    LABEL* LABEL     r--   Image label
      M2V  VIDEO     rw+   MPEG Video Stream
      M4V  VIDEO     rw+   Raw VIDEO-4 Video
      MAC* MAC       r--   MAC Paint
      MAP* MAP       rw-   Colormap intensities and indices
     MASK* MASK      rw+   Image Clip Mask
      MAT  MAT       rw+   MATLAB level 5 image format
    MATTE* MATTE     -w+   MATTE format
      MDC  DNG       r--   Minolta Digital Camera Raw Format (0.21.3-Release)
      MEF  DNG       r--   Mamiya Raw Format (0.21.3-Release)
     MIFF* MIFF      rw+   Magick Image File Format
      MKV  VIDEO     rw+   Multimedia Container
      MNG* PNG       rw+   Multiple-image Network Graphics (libpng 1.6.44)
             See http://www.libpng.org/pub/mng/ for details about the MNG
             format.
     MONO* MONO      rw-   Raw bi-level bitmap
      MOS  DNG       r--   Aptus Leaf Raw Format (0.21.3-Release)
      MOV  VIDEO     rw+   MPEG Video Stream
      MP4  VIDEO     rw+   VIDEO-4 Video Stream
      MPC* MPC       rw+   Magick Pixel Cache image format
     MPEG  VIDEO     rw+   MPEG Video Stream
      MPG  VIDEO     rw+   MPEG Video Stream
      MPO* JPEG      r--   Joint Photographic Experts Group JFIF format (libjpeg-turbo 3.0.3)
      MRW  DNG       r--   Sony (Minolta) Raw Format (0.21.3-Release)
      MSL* MSL       rw+   Magick Scripting Language
     MSVG* SVG       rw+   ImageMagick's own SVG internal renderer
      MTV* MTV       rw+   MTV Raytracing image format
      MVG* MVG       rw-   Magick Vector Graphics
      NEF  DNG       r--   Nikon Digital SLR Camera Raw Format (0.21.3-Release)
      NRW  DNG       r--   Nikon Digital SLR Camera Raw Format (0.21.3-Release)
     NULL* NULL      rw-   Constant image of uniform color
      ORA  ORA       r--   OpenRaster format
      ORF  DNG       r--   Olympus Digital Camera Raw Format (0.21.3-Release)
      OTB* OTB       rw-   On-the-air bitmap
      OTF* TTF       r--   Open Type font (Freetype 2.13.3)
      PAL* UYVY      rw-   16bit/pixel interleaved YUV
     PALM* PALM      rw+   Palm pixmap
      PAM* PNM       rw+   Common 2-dimensional bitmap format
    PANGO* PANGO     r--   Pango Markup Language (Pangocairo 1.45.2)
  PATTERN* PATTERN   r--   Predefined pattern
      PBM* PNM       rw+   Portable bitmap format (black and white)
      PCD* PCD       rw-   Photo CD
     PCDS* PCD       rw-   Photo CD
      PCL  PCL       rw+   Printer Control Language
      PCT* PICT      rw-   Apple Macintosh QuickDraw/PICT
      PCX* PCX       rw-   ZSoft IBM PC Paintbrush
      PDB* PDB       rw+   Palm Database ImageViewer Format
      PDF  PDF       rw+   Portable Document Format
     PDFA  PDF       rw+   Portable Document Archive Format
      PEF  DNG       r--   Pentax Electronic Raw Format (0.21.3-Release)
      PES* PES       r--   Embrid Embroidery Format
      PFA* TTF       r--   Postscript Type 1 font (ASCII) (Freetype 2.13.3)
      PFB* TTF       r--   Postscript Type 1 font (binary) (Freetype 2.13.3)
      PFM* PNM       rw+   Portable float format
      PGM* PNM       rw+   Portable graymap format (gray scale)
      PGX* PGX       rw-   JPEG 2000 uncompressed format
      PHM* PNM       rw+   Portable half float format
    PICON* XPM       rw-   Personal Icon
     PICT* PICT      rw-   Apple Macintosh QuickDraw/PICT
      PIX* PIX       r--   Alias/Wavefront RLE image format
    PJPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 3.0.3)
   PLASMA* PLASMA    r--   Plasma fractal image
      PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.44)
             See http://www.libpng.org/ for details about the PNG format.
    PNG00* PNG       rw-   PNG inheriting bit-depth, color-type from original, if possible
    PNG24* PNG       rw-   opaque or binary transparent 24-bit RGB
    PNG32* PNG       rw-   opaque or transparent 32-bit RGBA
    PNG48* PNG       rw-   opaque or binary transparent 48-bit RGB
    PNG64* PNG       rw-   opaque or transparent 64-bit RGBA
     PNG8* PNG       rw-   8-bit indexed with optional binary transparency
      PNM* PNM       rw+   Portable anymap
POCKETMOD  PDF       rw+   Pocketmod Personal Organizer
      PPM* PNM       rw+   Portable pixmap format (color)
       PS  PS        rw+   PostScript
      PS2  PS2       -w+   Level II PostScript
      PS3  PS3       -w+   Level III PostScript
      PSB* PSD       rw+   Adobe Large Document Format
      PSD* PSD       rw+   Adobe Photoshop bitmap
     PTIF* TIFF      rw+   Pyramid encoded TIFF
             Compression options: None, Fax/Group3, Group4, JBIG, JPEG, LERC, LZW, LZMA, RLE, ZIP, ZSTD, WEBP
      PWP* PWP       r--   Seattle Film Works
      QOI* QOI       rw-   Quite OK image format
RADIAL-GRADIENT* GRADIENT  r--   Gradual radial passing from one shade to another
      RAF  DNG       r--   Fuji CCD-RAW Graphic Raw Format (0.21.3-Release)
      RAS* SUN       rw+   SUN Rasterfile
      RAW  DNG       r--   Raw (0.21.3-Release)
      RGB* RGB       rw+   Raw red, green, and blue samples
   RGB565* RGB       r--   Raw red, green, blue samples in 565 format
     RGBA* RGB       rw+   Raw red, green, blue, and alpha samples
     RGBO* RGB       rw+   Raw red, green, blue, and opacity samples
      RGF* RGF       rw-   LEGO Mindstorms EV3 Robot Graphic Format (black and white)
      RLA* RLA       r--   Alias/Wavefront image
      RLE* RLE       r--   Utah Run length encoded image
      RMF  DNG       r--   Raw Media Format (0.21.3-Release)
     RSVG* SVG       rw+   Librsvg SVG renderer (RSVG 2.40.20)
      RW2  DNG       r--   Panasonic Lumix Raw Format (0.21.3-Release)
      RWL  DNG       r--   Leica Raw Format (0.21.3-Release)
      SCR* SCR       r--   ZX-Spectrum SCREEN$
SCREENSHOT* SCREENSHO r--   Screen shot
      SCT* SCT       r--   Scitex HandShake
      SFW* SFW       r--   Seattle Film Works
      SGI* SGI       rw+   Irix RGB image
    SHTML* HTML      -w-   Hypertext Markup Language and a client-side image map
      SIX* SIXEL     rw-   DEC SIXEL Graphics Format
    SIXEL* SIXEL     rw-   DEC SIXEL Graphics Format
SPARSE-COLOR* TXT       -w+   Sparse Color
      SR2  DNG       r--   Sony Raw Format 2 (0.21.3-Release)
      SRF  DNG       r--   Sony Raw Format (0.21.3-Release)
      SRW  DNG       r--   Samsung Raw Format (0.21.3-Release)
  STEGANO* STEGANO   r--   Steganographic image
      STI  DNG       r--   Sinar CaptureShop Raw Format (0.21.3-Release)
   STRIMG* STRIMG    rw-   String to image and back
      SUN* SUN       rw+   SUN Rasterfile
      SVG* SVG       rw+   Scalable Vector Graphics (RSVG 2.40.20)
     SVGZ* SVG       rw+   Compressed Scalable Vector Graphics (RSVG 2.40.20)
     TEXT* TXT       r--   Text
      TGA* TGA       rw-   Truevision Targa image
THUMBNAIL* THUMBNAIL -w+   EXIF Profile Thumbnail
     TIFF* TIFF      rw+   Tagged Image File Format (LIBTIFF, Version 4.7.0)
             Compression options: None, Fax/Group3, Group4, JBIG, JPEG, LERC, LZW, LZMA, RLE, ZIP, ZSTD, WEBP
   TIFF64* TIFF      rw+   Tagged Image File Format (64-bit) (LIBTIFF, Version 4.7.0)
             Compression options: None, Fax/Group3, Group4, JBIG, JPEG, LERC, LZW, LZMA, RLE, ZIP, ZSTD, WEBP
     TILE* TILE      r--   Tile image with a texture
      TIM* TIM       r--   PSX TIM
      TM2* TIM2      r--   PS2 TIM2
      TTC* TTF       r--   TrueType font collection (Freetype 2.13.3)
      TTF* TTF       r--   TrueType font (Freetype 2.13.3)
      TXT* TXT       rw+   Text
     UBRL* BRAILLE   -w-   Unicode Text format
    UBRL6* BRAILLE   -w-   Unicode Text format 6dot
      UIL* UIL       -w-   X-Motif UIL table
     UYVY* UYVY      rw-   16bit/pixel interleaved YUV
      VDA* TGA       rw-   Truevision Targa image
    VICAR* VICAR     rw-   Video Image Communication And Retrieval
      VID* VID       rw+   Visual Image Directory
     VIFF* VIFF      rw+   Khoros Visualization image
     VIPS* VIPS      rw+   VIPS image
      VST* TGA       rw-   Truevision Targa image
     WBMP* WBMP      rw-   Wireless Bitmap (level 0) image
     WEBM  VIDEO     rw+   Open Web Media
     WEBP* WEBP      rw+   WebP Image Format (libwebp 1.4.0 [020F])
      WMF  EMF       r--   Windows Meta File
      WMV  VIDEO     rw+   Windows Media Video
      WPG* WPG       rw-   Word Perfect Graphics
      X3F  DNG       r--   Sigma Camera RAW Format (0.21.3-Release)
      XBM* XBM       rw-   X Windows system bitmap (black and white)
       XC* XC        r--   Constant image uniform color
      XCF* XCF       r--   GIMP image
      XPM* XPM       rw-   X Windows system pixmap (color)
      XPS  XPS       r--   Microsoft XML Paper Specification
       XV* VIFF      rw+   Khoros Visualization image
     YAML  YAML      -w+   The image format and characteristics
    YCBCR* YCBCR     rw+   Raw Y, Cb, and Cr samples
   YCBCRA* YCBCR     rw+   Raw Y, Cb, Cr, and alpha samples
      YUV* YUV       rw-   CCIR 601 4:1:1 or 4:2:2

* native blob support
r read support
w write support
+ support for multiple images

**Comment by LOuroboros** [comment]
> On IM 7, use magick, not magick convert. So try
> 
> `magick input.png -define icon:auto-resize input.ico`

I can't exactly tell if it worked or not because I already used a web service to quickly turn that .png into a .ico file, but I grabbed a different .png and turned it into a .ico using `magick` instead of `magick convert` like you suggested, and that worked.

I guess that for the time being I'll keep using the binaries from "ImageMagick-7.1.1-43-portable-Q16-x64.zip" and see how things go.

Thanks for the reply!

**Comment by francoisdejgr** [comment]
Greetings

Hope this helps, including 2 log files one where I do identify and then I do crop
The commands
magick identify test.png
test.png PNG 482x373 482x373+0+0 8-bit sRGB 62835B 0.001u 0:00.000

magick test.png: -crop 40x30+10+10  +repage  repage.png
magick.exe: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

[identify-test-png.log](https://github.com/user-attachments/files/18463312/identify-test-png.log)

[crop-test.log](https://github.com/user-attachments/files/18463314/crop-test.log)

**Comment by fmw42** [comment]
Only Internal Imagemagick images such as logo: and rose: use the ":" All other images just use the normal suffix with no ":"

**Comment by khlr** [comment]
I was having exactly the same issue:

    magick.exe convert icon_16.png favicon.ico
    
    magick.exe: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

I had tried the portable version all the time (ImageMagick-7.1.1-43-portable-Q16-x64). After I used the installation version, it worked straight away. So it could be related to portable.

**Comment by fmw42** [comment]
On IM 7, use magick, not magick convert. So try

`magick.exe icon_16.png ICO:favicon.ico`

Does that work?

**Comment by khlr** [comment]
Hi Fred! Thanks! For a simple conversion, this works.

But I was effectively trying was to create an ICO from two PNGs. A detailed PNGs for higher resolutions and another PNG with less details for smaller resolutions.

I first tried this (portable with convert):

    magick.exe convert simple.png[16x16] simple.png[32x32] simple.png[48x48] detailed.png[64x64] detailed.png[128x128] detailed.png[256x256] define icon:auto-resize=256,128,64,48,32,16 output1.ico
    
    magick.exe: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

And even if I try your suggestion (omitting convert), I get the same error (using portable):

    magick.exe simple.png[16x16] simple.png[32x32] simple.png[48x48] detailed.png[64x64] detailed.png[128x128] detailed.png[256x256] define icon:auto-resize=256,128,64,48,32,16 output1.ico
    
    magick.exe: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

**Comment by fmw42** [comment]
I am not an expert on ICOs.  I don't think IM can create ICOs from multiple input images. It creates multiple resolutions from one image.  However, I will defer to the IM developers for further comments.

**Comment by khlr** [comment]
Yes, it actually can. I was able to do it with the installable version. Unfortunately, it doesn't work with the portable version.

**Comment by satano** [comment]
Hello. I can confirm, that this error has something to do with portable version – or with versions not installed with standard Windows installer. I installed ImageMagick using `winget` on Windows 11. I tried to convert some image and got the same error:

> magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

I uninstalled it using `winget` and installed it using standard installer downloaded from ImageMagic web page. Now it works.

**Comment by dlemstra** [comment]
`magick convert` no longer works with the portable version. Only the installers offer support for this deprecated feature.

**Comment by fmw42** [comment]
On IM 7, you should use magick, **not** magick convert.   Magick convert is like convert, which only runs on IM 6 and is now deprecated.
